# |= 할당 연산자 
FirstValue = 3 
SecondValue = 2 
FirstValue |= SecondValue 
print("|=, FristValue",FirstValue)
print("|=, SecondValue", SecondValue) 
# 2 # ^= 할당 연산자 
FirstValue = 3
SecondValue = 2 
FirstValue ^= SecondValue 
print("^= FirstValue ", FirstValue) 
print("^= SecondValue ", SecondValue) # 2 
# >>= 할당 연산자 
FirstValue = 3
SecondValue = 2 
FirstValue >>= SecondValue 
print(">>= FirstValue", FirstValue) 
print(">>= SecondValue", SecondValue) 
# 2 # <<= 할당 연산자 
FirstValue = 3 
SecondValue = 2 
FirstValue <<= SecondValue 
print("<<= FirstValue", FirstValue) 
print(">>= SecondValue", SecondValue)